config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists
  resources :my_lists

    # get 'lists/index'
    root 'lists#index'
    # get '/lists/', to: 'lists#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	belongs_to :place
	has_and_belongs_to_many :user
end

app/models/my_list.rb
class MyList < ApplicationRecord
	belongs_to :list
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :lists	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :my_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @places = Place.order :name
  end

  def show
    @place = Place.find(params[:place_id])
  end
end	

app/controllers/my_lists_controller.rb
class MyListsController < ApplicationController
   before_action :set_my_list, only: [:show, :edit, :update, :destroy]

  # GET /my_lists
  # GET /my_lists.json
  def index
    @my_lists = MyList.all
  end

  # GET /my_lists/1
  # GET /my_lists/1.json
  def show
    @my_lists = List.new
  end

  # GET /my_lists/new
  def new
    @list = MyList.new
  end

  # GET /my_lists/1/edit
  def edit
  end

  # POST /my_lists
  # POST /my_lists.json
  def create
    @my_list = MyList.new#(my_list_params)

    # respond_to do |format|
    #   if @list.save
    #     format.html { redirect_to @my_list, notice: 'My list was successfully created.' }
    #     format.json { render :show, status: :created, location: @my_list }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @my_list.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /my_lists/1
  # PATCH/PUT /my_lists/1.json
  def update
    respond_to do |format|
      if @my_list.update(my_list_params)
        format.html { redirect_to @my_list, notice: 'My list was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_list }
      else
        format.html { render :edit }
        format.json { render json: @my_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_lists/1
  # DELETE /my_lists/1.json
  def destroy
    @my_list.destroy
    respond_to do |format|
      format.html { redirect_to my_lists_url, notice: 'My list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_list
      @my_list = MyList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_list_params
      params.require(:my_list).permit(:place_id, :name, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/my_list_helper.rb
module MyListHelper
end

app/helpers/my_lists_helper.rb
module MyListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

    <title>Packing</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pakd</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/lists">Create a new list</a></li>
      </ul>
        <ul class="nav navbar-nav">
        <li class="active"><a href="/my_lists">My Lists</a></li>
      </ul>
    </div>
  </div>
</nav>
  <% if notice %>

  	<p class="alert alert-success"><%= notice %></p>
	<% end %>

	<% if alert %>
 		<p class="alert alert-danger"><%= alert %></p>
	<% end %>

<div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<br>
<br>
<div align="center">
<h1>So, you want to travel (:</h1>
</div>

<div style= "margin-left:40px">
<h3> Where are you going? </h3>
</div>  

<%= form_tag(list_path(:place_id), method: "get") do %>
<br>

<div align="center">
<%= select_tag :place_id, options_from_collection_for_select(@places, "id", "name"), prompt: nil , class: "select"%>
<br>
<br>
<%= submit_tag "Go!", class: "btn btn-default go" %>
<% end %>
</div>

app/views/lists/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<%= link_to 'Back', lists_path %>
<div align="center">
<h1> <%= @place.name %> </h1> <br>
</div>

<h3> You'll need to bring: </h3>

<%= form_tag(my_lists_path, method: "get") do %>
<% @place.lists.each do |list| %>
	<p>
		<% list.items.each do |s| %>
			<%= check_box_tag s %><td> &nbsp; &nbsp;</td><%= s %><br>
		<% end %>
	</p>
	
<% end %>

<div align="center">
	<%= submit_tag "Save", class: "btn btn-default" %>
</div>
<% end %>

app/views/my_lists/_form.html.erb
<%= form_for(my_list) do |f| %>
  <% if my_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_list.errors.count, "error") %> prohibited this my_list from being saved:</h2>

      <ul>
      <% my_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_id %>
    <%= f.text_field :place_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_lists/edit.html.erb
<h1>Editing My List</h1>

<%= render 'form', my_list: @my_list %>

<%= link_to 'Show', @my_list %> |
<%= link_to 'Back', my_lists_path %>

app/views/my_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Lists</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_lists.each do |my_list| %>
      <tr>
        <td><%= my_list.place_id %></td>
        <td><%= my_list.name %></td>
        <td><%= my_list.date %></td>
        <td><%= link_to 'Show', my_list %></td>
        <td><%= link_to 'Edit', edit_my_list_path(my_list) %></td>
        <td><%= link_to 'Destroy', my_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_my_list_path %>

app/views/my_lists/new.html.erb
<h1>New My List</h1>

<%= render 'form', my_list: @my_list %>

<%= link_to 'Back', my_lists_path %>

app/views/my_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @list%>
</p>


<%= link_to 'Back', my_lists_path %>